pub const JNI_GET_HANDLER: &str = "Failed to get JNI handler pointer";
pub const JNI_SET_HANDLER: &str = "Failed to set JNI handler pointer";
pub const JNI_ARRAY_LENGHT: &str = "Failed to get JNI array length";
pub const JNI_ARRAY_ELEMENT: &str = "Failed to get JNI array element";
pub const JNI_ARRAY_ELEMENTS: &str = "Failed to get JNI array elements";
pub const JNI_MAKE_STRING: &str = "Failed to prepare a JNI string";
pub const JNI_FIND_CLASS: &str = "Failed find a JNI class";
pub const JNI_NEW_STRING: &str = "Failed to create a new JNI string";
pub const JNI_NEW_ARRAY: &str = "Failed to create a new JNI array";
